import { NgModule } from '@angular/core';
import {MatCardModule,
    MatButtonModule,
    MatTableModule,
    MatDialogModule,
    MatInputModule,
    MatSelectModule,
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatPaginatorModule,
    MatSortModule, 
    MatGridListModule, 
    MatMenuModule, 
    MatFormFieldModule, 
    MatNativeDateModule,
    MatDatepickerModule} from '@angular/material';
    

@NgModule({
  imports: [MatCardModule,
    MatButtonModule,
    MatTableModule,
    MatDialogModule,
    MatInputModule,
    MatSelectModule,
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatPaginatorModule,
    MatSortModule, 
    MatGridListModule, 
    MatMenuModule, 
    MatFormFieldModule,
    MatDatepickerModule,
    MatNativeDateModule],
  exports: [MatCardModule,
    MatButtonModule,
    MatTableModule,
    MatDialogModule,
    MatInputModule,
    MatSelectModule,
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatPaginatorModule,
    MatSortModule, 
    MatGridListModule, 
    MatMenuModule, 
    MatFormFieldModule,
    MatDatepickerModule,
    MatNativeDateModule],
})
export class MaterialModule { }